### ISSUE TITLE
meeting-boxing-related bugs in site

### ISSUE THREAD

**Issue by ianklatzco** [sigpwny/sigpwny.github.io#2]
- [x]  meetings page in sidebar (easy)
- [ ]  ~~on index.html, meetings are sorted oldest top, newest bottom. this should be flipped.~~ forget it it's not worth doing
- [x]  `more meetings` redirects to list. it should redirect to a list of meetings (probably just sigpwny.github.io/meetings.html)
- [ ] revert list.html to blog posts. make a separate lists.html that is instead meetings.html

**Comment by ianklatzco** [comment]
@177912968040677376

**Comment by ianklatzco** [comment]
@177912968040677376

**Comment by ianklatzco** [comment]
@trevorm4 could you try tackling these when you get a chance?

**Comment by trevorm4** [comment]
Added meetings page to sidebar (list.html) and more meetings redirects there as well

**Comment by ianklatzco** [comment]
list.html used to be blog posts. can you please revert it to that, and make a separate meetings-list.html?

**Comment by ianklatzco** [comment]
this will require learning some about jekyll.

**Comment by ianklatzco** [comment]
yeah so:
* revert list.html
* use [https://sigpwny.github.io/meetings](https://sigpwny.github.io/meetings)

**Comment by ianklatzco** [comment]
https://github.com/sigpwny/sigpwny.github.io/blob/master/_meetings/README.md#jekyll-details-dont-read-unless-youre-website-admin
